### PR TITLE
Merge Dev with Master

### PR DESCRIPTION
**Pull request by jeremyliu8**
Creating a Pull Request to merge Dev into Master. This will be a milestone of what we presented on our first demo. We will use this to track our progress with future demos as well.

### CODE REVIEW

**Comment by jeremyliu8** [comment]
Hey guys, I am just doing this for learning purposes. I created a pull request on Git so we can talk about the changes before we actually merge. This is a collaborative project, so we need to discuss changes that we made and all agree together. I will not merge with master until everyone submits a comment to give me the 'OK'!

**Comment by jeremyliu8** [comment]
Now that we updated all database interactions with mysqli object-oriented. We are ready to merge.

**Comment by csissoyev8** [comment]
first

**Comment by FightingGinger** [comment]
Yeah look good and all the databases are mysqli OOP. Everything looks good to me.

**Comment by jeremyliu8** [comment]
Okay I will merge now.

**Pull request merged**
